package com.mrcrayfish.vehicle.datagen;

import com.mrcrayfish.vehicle.client.CameraProperties;
import com.mrcrayfish.vehicle.client.model.SpecialModels;
import com.mrcrayfish.vehicle.common.Seat;
import com.mrcrayfish.vehicle.common.cosmetic.CosmeticProperties;
import com.mrcrayfish.vehicle.common.cosmetic.StandardCosmetics;
import com.mrcrayfish.vehicle.common.cosmetic.actions.OpenableAction;
import com.mrcrayfish.vehicle.common.entity.Transform;
import com.mrcrayfish.vehicle.entity.EngineType;
import com.mrcrayfish.vehicle.entity.FuelFillerType;
import com.mrcrayfish.vehicle.entity.Wheel;
import com.mrcrayfish.vehicle.entity.properties.PlaneProperties;
import com.mrcrayfish.vehicle.entity.properties.PoweredProperties;
import com.mrcrayfish.vehicle.entity.properties.TrailerProperties;
import com.mrcrayfish.vehicle.entity.properties.VehicleProperties;
import com.mrcrayfish.vehicle.init.ModEntities;
import com.mrcrayfish.vehicle.init.ModSounds;
import net.minecraft.data.DataGenerator;
import net.minecraft.util.ResourceLocation;

/**
 * Author: MrCrayfish
 */
public class VehiclePropertiesGen extends VehiclePropertiesProvider
{
    public VehiclePropertiesGen(DataGenerator generator)
    {
        super(generator);
    }

    @Override
    protected void registerProperties()
    {
        this.add(ModEntities.QUAD_BIKE.get(), VehicleProperties.builder()
                .setAxleOffset(-0.5F)
                .setBodyTransform(Transform.create(1.2))
                .setDisplayTransform(Transform.create(1.5))
                .setHeldOffset(4.0, 3.5, 0.0)
                .setCanTowTrailers(true)
                .setTowBarPosition(0.0, 0.0, -16.0)
                .setTrailerOffset(0.0, 0.0, -0.55)
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.LEFT)
                        .setPosition(Wheel.Position.FRONT)
                        .setOffset(4.5, 0.0, 9.5)
                        .setScale(1.1))
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.RIGHT)
                        .setPosition(Wheel.Position.FRONT)
                        .setOffset(4.5, 0.0, 9.5)
                        .setScale(1.1))
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.LEFT)
                        .setPosition(Wheel.Position.REAR)
                        .setOffset(4.5, 0.0, -9.5)
                        .setScale(1.1)
                        .setParticles(true))
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.RIGHT)
                        .setPosition(Wheel.Position.REAR)
                        .setOffset(4.5, 0.0, -9.5)
                        .setScale(1.1)
                        .setParticles(true))
                .addSeat(Seat.of(0.0, 5.0, -4.0, true))
                .addSeat(Seat.of(0.0, 5.5, -12.0))
                .setCanChangeWheels(true)
                .setCanBePainted(true)
                .addExtended(PoweredProperties.builder()
                        .setEngineType(EngineType.SMALL_MOTOR)
                        .setEnginePower(15F)
                        .setFuelFillerTransform(Transform.create(0.0, 11.2876, 7.5, -90.0, 0.0, 0.0, 0.6))
                        .setIgnitionTransform(Transform.create(-5.0, 4.5, 6.5, -45.0, 0.0, 0.0, 0.5))
                        .setFrontAxleOffset(10.5)
                        .setRearAxleOffset(-10.5)
                        .setEnergyCapacity(20000F)
                        .setEngineSound(ModSounds.ENTITY_QUAD_BIKE_ENGINE.getId())
                        .setFuelFillerType(FuelFillerType.SMALL)
                        .setRenderEngine(true)
                        .setEngineTransform(Transform.create(0.0, 1.0, -1.0, 0.0, 180.0, 0.0, 0.5))
                        .build()));

        this.add(ModEntities.DIRT_BIKE.get(), VehicleProperties.builder()
                .setDisplayTransform(Transform.create(1.4))
                .setHeldOffset(0.0, 3.5, 0.0)
                .setTrailerOffset(0, -0.0625, -0.3125)
                .addWheel(Wheel.builder()
                        .setPosition(Wheel.Position.FRONT)
                        .setOffset(0.0, 0.0, 14.08)
                        .setScale(0.9375, 1.4, 1.4)
                        .setRender(false))
                .addWheel(Wheel.builder()
                        .setPosition(Wheel.Position.REAR)
                        .setOffset(0.0, 0.0, -11.61F)
                        .setScale(0.9375, 1.4, 1.4)
                        .setParticles(true))
                .addSeat(Seat.of(0.0, 8.0, -2.0, true))
                .addSeat(Seat.of(0.0, 9.0, -9.0))
                .setCanChangeWheels(true)
                .setCanBePainted(true)
                .setCamera(CameraProperties.builder()
                        .setPosition(0, 1.75, 0))
                .addExtended(PoweredProperties.builder()
                        .setEngineType(EngineType.SMALL_MOTOR)
                        .setEnginePower(16F)
                        .setMinEnginePitch(0.85F)
                        .setMaxEnginePitch(1.5F)
                        .setEngineTransform(Transform.create(0.0, 1.0, 0.0, 0.0, 180.0, 0.0, 0.6))
                        .setFuelFillerTransform(Transform.create(0.0, 14.775, 3.603, 67.5, 180.0, 0.0, 0.6))
                        .setFrontAxleOffset(14.08)
                        .setRearAxleOffset(-11.61)
                        .setEnergyCapacity(20000F)
                        .setEnergyConsumptionPerTick(0.35F)
                        .setCanLockWithKey(false)
                        .setShowExhaustFumes(true)
                        .setExhaustFumesPosition(-1, 16, -16) //TODO I think this will be wrong
                        .setRenderEngine(true)
                        .setEngineSound(ModSounds.ENTITY_DIRT_BIKE_ENGINE.getId())
                        .setFuelFillerType(FuelFillerType.SMALL)
                        .build()));

        this.add(ModEntities.GO_KART.get(), VehicleProperties.builder()
                .setAxleOffset(-1.0F)
                .setDisplayTransform(Transform.create(0.0, 0.0, -0.15, 0.0, 0.0, 0.0, 1.5))
                .setHeldOffset(3.0, 0.5, 0.0)
                .setTrailerOffset(0.0, -0.03125, -0.375)
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.LEFT)
                        .setPosition(Wheel.Position.FRONT)
                        .setOffset(7.0, 0.0, 8.75)
                        .setScale(1.0, 0.8, 0.8))
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.RIGHT)
                        .setPosition(Wheel.Position.FRONT)
                        .setOffset(7.0, 0.0, 8.75)
                        .setScale(1.0, 0.8, 0.8))
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.LEFT)
                        .setPosition(Wheel.Position.REAR)
                        .setOffset(7.0, 0.25, -9.5)
                        .setScale(1.0, 0.0, 0.0)
                        .setAutoScale(true)
                        .setParticles(true))
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.RIGHT)
                        .setPosition(Wheel.Position.REAR)
                        .setOffset(7.0, 0.25, -9.5)
                        .setScale(1.0, 0.0, 0.0)
                        .setAutoScale(true)
                        .setParticles(true))
                .addSeat(Seat.of(0.0, -3.0, -1.5, true))
                .setCanChangeWheels(true)
                .setCanBePainted(true)
                .setCamera(CameraProperties.builder()
                        .setPosition(0, 1, 0))
                .addExtended(PoweredProperties.builder()
                        .setEngineType(EngineType.SMALL_MOTOR)
                        .setEnginePower(18F)
                        .setMinEnginePitch(0.8F)
                        .setMaxEnginePitch(1.6F)
                        .setEngineTransform(Transform.create(0.0, 2.0, -9.0, 0.0, 180.0, 0.0, 0.8))
                        .setFrontAxleOffset(9.0)
                        .setRearAxleOffset(-9.5)
                        .setEnergyConsumptionPerTick(0.5F)
                        .setCanLockWithKey(false)
                        .setShowExhaustFumes(true)
                        .setExhaustFumesPosition(0, 8, -16) // TODO might be wrong
                        .setRenderEngine(true)
                        .setEngineSound(ModSounds.ENTITY_GO_KART_ENGINE.getId())
                        .build()));

        this.add(ModEntities.GOLF_CART.get(), VehicleProperties.builder()
                .setAxleOffset(-0.5F)
                .setBodyTransform(Transform.create(1.15))
                .setDisplayTransform(Transform.create(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.25))
                .setHeldOffset(1.5, 2.5, 0.0)
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.LEFT)
                        .setPosition(Wheel.Position.FRONT)
                        .setOffset(9.0, 0.0, 16.0)
                        .setScale(1.1))
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.RIGHT)
                        .setPosition(Wheel.Position.FRONT)
                        .setOffset(9.0, 0.0, 16.0)
                        .setScale(1.1))
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.LEFT)
                        .setPosition(Wheel.Position.REAR)
                        .setOffset(9.0, 0.0, -12.5)
                        .setScale(1.1)
                        .setParticles(true))
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.RIGHT)
                        .setPosition(Wheel.Position.REAR)
                        .setOffset(9.0, 0.0, -12.5)
                        .setScale(1.1)
                        .setParticles(true))
                .addSeat(Seat.of(5.5, 5.0, -6.0, true))
                .addSeat(Seat.of(-5.5, 5.0, -6.0))
                .addSeat(Seat.of(5.5, 5.0, -15.0, 180F))
                .addSeat(Seat.of(-5.5, 5.0, -15.0, 180F))
                .setCanChangeWheels(true)
                .setCanBePainted(true)
                .setCanFitInTrailer(false)
                .setCamera(CameraProperties.builder()
                        .setDistance(5.0)
                        .setPosition(0, 2, 0))
                .addExtended(PoweredProperties.builder()
                        .setEngineType(EngineType.ELECTRIC_MOTOR)
                        .setEnginePower(25F)
                        .setMaxEnginePitch(1.0F)
                        .setFuelFillerTransform(Transform.create(-13, 5.5, -6.0, 0.0, -90.0, 0.0, 0.5))
                        .setIgnitionTransform(Transform.create(-8.5, 2.75, 8.5, -67.5, 0.0, 0.0, 0.5))
                        .setFrontAxleOffset(16.0)
                        .setRearAxleOffset(-12.5)
                        .setEngineSound(ModSounds.ENTITY_VEHICLE_HELICOPTER_ROTOR.getId())
                        .build()));

        this.add(ModEntities.JET_SKI.get(), VehicleProperties.builder()
                .setAxleOffset(2.75F)
                .setBodyTransform(Transform.create(0.0, 0.0, 0.25, 0.0, 0.0, 0.0, 1.25))
                .setDisplayTransform(Transform.create(0.0F, 0.0F, -7.2F, 0.0F, 0.0F, 0.0F, 1.5F))
                .setHeldOffset(6.0, 0.0, 0.0)
                .setTrailerOffset(0.0, -0.09375, -0.65)
                .addSeat(Seat.of(0.0, 5.0, 0.0, true))
                .addSeat(Seat.of(0.0, 5.0, -7.0))
                .setCanBePainted(true)
                .addExtended(PoweredProperties.builder()
                        .setEngineType(EngineType.SMALL_MOTOR)
                        .setEnginePower(18F)
                        .setMinEnginePitch(1.2F)
                        .setMaxEnginePitch(2.2F)
                        .setFuelFillerTransform(Transform.create(0.0, 9.25, 8.5, -90, 0.0, 0.0, 0.35))
                        .setEnergyConsumptionPerTick(0.5F)
                        .setCanLockWithKey(false)
                        .setEngineSound(ModSounds.ENTITY_JET_SKI_ENGINE.getId())
                        .setFuelFillerType(FuelFillerType.SMALL)
                        .build()));

        this.add(ModEntities.LAWN_MOWER.get(), VehicleProperties.builder()
                .setAxleOffset(-2.0F)
                .setBodyTransform(Transform.create(1.25))
                .setDisplayTransform(Transform.create(1.5))
                .setHeldOffset(12.0, -1.5, 0.0)
                .setCanTowTrailers(true)
                .setTowBarPosition(0.0, 0.0, -16.0)
                .setTrailerOffset(0.0, -0.01, -1.0)
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.LEFT)
                        .setPosition(Wheel.Position.FRONT)
                        .setOffset(6.0, 0.0, 13.5)
                        .setScale(0.0, 0.0, 0.0)
                        .setAutoScale(true))
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.RIGHT)
                        .setPosition(Wheel.Position.FRONT)
                        .setOffset(6.0, 0.0, 13.5)
                        .setScale(0.0, 0.0, 0.0)
                        .setAutoScale(true))
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.LEFT)
                        .setPosition(Wheel.Position.REAR)
                        .setOffset(5.0, 0.8, -10.7)
                        .setScale(0.97)
                        .setParticles(true))
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.RIGHT)
                        .setPosition(Wheel.Position.REAR)
                        .setOffset(5.0, 0.8, -10.7)
                        .setScale(0.97)
                        .setParticles(true))
                .addSeat(Seat.of(0.0, 7.0, -9.0, true))
                .setCanChangeWheels(true)
                .setCanBePainted(true)
                .addExtended(PoweredProperties.builder()
                        .setEngineType(EngineType.SMALL_MOTOR)
                        .setEnginePower(8F)
                        .setFuelFillerTransform(Transform.create(-4.5, 10.0, 4.5, 0.0, -90.0, 0.0, 0.5))
                        .setIgnitionTransform(Transform.create(-5.0, 4.5, 6.5, -45, 0.0, 0.0, 0.5))
                        .setFrontAxleOffset(13.5)
                        .setRearAxleOffset(-10.7)
                        .setEnergyCapacity(5000F)
                        .setCanLockWithKey(false)
                        .setEngineSound(ModSounds.ENTITY_QUAD_BIKE_ENGINE.getId())
                        .build()));

        this.add(ModEntities.MINI_BUS.get(), VehicleProperties.builder()
                .setAxleOffset(1.0F)
                .setBodyTransform(Transform.create(1.3))
                .setDisplayTransform(Transform.create(1.0))
                .setHeldOffset(0.0, 3.5, 0.0)
                .setCanTowTrailers(true)
                .setTowBarPosition(0.0, 0.0, -25.0)
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.LEFT)
                        .setPosition(Wheel.Position.FRONT)
                        .setOffset(9.0, 0.0, 13.5)
                        .setScale(0.9375, 1.19, 1.19)
                        .setParticles(true))
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.RIGHT)
                        .setPosition(Wheel.Position.FRONT)
                        .setOffset(9.0, 0.0, 13.5)
                        .setScale(0.9375, 1.19, 1.19)
                        .setParticles(true))
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.LEFT)
                        .setPosition(Wheel.Position.REAR)
                        .setOffset(9.0, 0.0, -13.5)
                        .setScale(0.9375, 1.19, 1.19)
                        .setParticles(true))
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.RIGHT)
                        .setPosition(Wheel.Position.REAR)
                        .setOffset(9.0, 0.0, -13.5)
                        .setScale(0.9375, 1.19, 1.19)
                        .setParticles(true))
                .addSeat(Seat.of(5.0, 3.0, 9.0, true))
                .addSeat(Seat.of(-5.0, 3.0, 9.0))
                .addSeat(Seat.of(5.0, 3.0, -3.0))
                .addSeat(Seat.of(-5.0, 3.0, -3.0))
                .addSeat(Seat.of(5.0, 3.0, -15.0))
                .setCanChangeWheels(true)
                .setCanBePainted(true)
                .setCamera(CameraProperties.builder()
                        .setDistance(6.0))
                .addExtended(PoweredProperties.builder()
                        .setEngineType(EngineType.LARGE_MOTOR)
                        .setEnginePower(14F)
                        .setMinEnginePitch(0.75F)
                        .setFuelFillerTransform(Transform.create(-12.0, 10.0, -8.75, 0.0, -90.0, 0.0, 0.5))
                        .setIgnitionTransform(Transform.create(0.0, 6.75, 19.5, -67.5, 0.0, 0.0, 0.5))
                        .setFrontAxleOffset(13.5)
                        .setRearAxleOffset(-13.5)
                        .setEnergyCapacity(30000F)
                        .setEnergyConsumptionPerTick(0.375F)
                        .setEngineSound(ModSounds.ENTITY_MINI_BUS_ENGINE.getId())
                        .build())
                .addCosmetic(CosmeticProperties.builder(StandardCosmetics.ROOF_FRAME)
                        .setOffset(0, 13, 0)
                        .addModelLocation(SpecialModels.MINI_BUS_COSMETIC_STOCK_ROOF.getModelLocation())
                        .addModelLocation(SpecialModels.MINI_BUS_COSMETIC_FRONT_ROOF.getModelLocation(),
                                StandardCosmetics.REAR,
                                StandardCosmetics.ROOF))
                .addCosmetic(CosmeticProperties.builder(StandardCosmetics.ROOF)
                        .setOffset(0, 22, 0)
                        .addModelLocation(SpecialModels.MINI_BUS_COSMETIC_ROOF_RACKS.getModelLocation()))
                .addCosmetic(CosmeticProperties.builder(StandardCosmetics.LEFT_DOOR)
                        .setOffset(11.5, 5, 20.5)
                        .addModelLocation(SpecialModels.MINI_BUS_COSMETIC_STOCK_LEFT_DOOR.getModelLocation())
                        .addAction(new OpenableAction(OpenableAction.Axis.Y, -75F, new ResourceLocation("vehicle:entity.vehicle.door.open"), new ResourceLocation("vehicle:entity.vehicle.door.close"), 12)))
                .addCosmetic(CosmeticProperties.builder(StandardCosmetics.RIGHT_DOOR)
                        .setOffset(-11.5, 5, 20.5)
                        .addModelLocation(SpecialModels.MINI_BUS_COSMETIC_STOCK_RIGHT_DOOR.getModelLocation())
                        .addAction(new OpenableAction(OpenableAction.Axis.Y, 75F, new ResourceLocation("vehicle:entity.vehicle.door.open"), new ResourceLocation("vehicle:entity.vehicle.door.close"), 12)))
                .addCosmetic(CosmeticProperties.builder(StandardCosmetics.LEFT_SLIDING_DOOR)
                        .setOffset(11.5, 5, -7.5)
                        .addModelLocation(SpecialModels.MINI_BUS_COSMETIC_STOCK_SLIDING_DOOR.getModelLocation())
                        .addAction(new OpenableAction(OpenableAction.Axis.Y, 105F, new ResourceLocation("vehicle:entity.vehicle.door.open"), new ResourceLocation("vehicle:entity.vehicle.door.close"), 20)))
                .addCosmetic(CosmeticProperties.builder(StandardCosmetics.REAR)
                        .setOffset(0, 6, -22.0)
                        .addModelLocation(SpecialModels.MINI_BUS_COSMETIC_AIRCON_LADDER_REAR_DECOR.getModelLocation()))
                .addCosmetic(CosmeticProperties.builder(StandardCosmetics.SEAT)
                        .setOffset(0, 5, 0)
                        .addModelLocation(SpecialModels.MINI_BUS_COSMETIC_STOCK_SEAT.getModelLocation()))
                .addCosmetic(CosmeticProperties.builder(StandardCosmetics.DASHBOARD)
                        .setOffset(0, 5, 16)
                        .addModelLocation(SpecialModels.MINI_BUS_COSMETIC_STOCK_DASHBOARD.getModelLocation()))
        );

        this.add(ModEntities.MOPED.get(), VehicleProperties.builder()
                .setAxleOffset(-1.0F)
                .setBodyTransform(Transform.create(1.2))
                .setDisplayTransform(Transform.create(0.0, 0.0, -0.25, 0.0, 0.0, 0.0, 1.5))
                .setHeldOffset(4.5, 2.0, 0.0)
                .setTrailerOffset(0.0, -0.03125, -0.65)
                .addWheel(Wheel.builder()
                        .setPosition(Wheel.Position.FRONT)
                        .setOffset(0.0, 0.0, 14.0884)
                        .setScale(0.6, 0.8, 0.8)
                        .setRender(false))
                .addWheel(Wheel.builder()
                        .setPosition(Wheel.Position.REAR)
                        .setOffset(0.0, 0.0, -6.7)
                        .setParticles(true)
                        .setScale(1, 0, 0)
                        .setAutoScale(true))
                .addSeat(Seat.of(0.0, 4.0, -1.0, true))
                .setCanChangeWheels(true)
                .setCanBePainted(true)
                .addExtended(PoweredProperties.builder()
                        .setEngineType(EngineType.SMALL_MOTOR)
                        .setEnginePower(12F)
                        .setMaxEnginePitch(1.2F)
                        .setIgnitionTransform(Transform.create(-2.5, 4.2, -1.5, 0.0, -90.0, 0.0, 0.2))
                        .setFrontAxleOffset(14.0)
                        .setRearAxleOffset(-6.7)
                        .setMaxSteeringAngle(45F)
                        .setEnergyCapacity(12000F)
                        .setEnergyConsumptionPerTick(0.225F)
                        .setCanLockWithKey(false)
                        .setEngineSound(ModSounds.ENTITY_MOPED_ENGINE.getId())
                        .build())
                .addCosmetic(CosmeticProperties.builder(StandardCosmetics.SEAT)
                        .setOffset(0, 7, -6.5)
                        .addModelLocation(SpecialModels.MOPED_COSMETIC_STOCK_SEAT.getModelLocation()))
                .addCosmetic(CosmeticProperties.builder(StandardCosmetics.TRAY)
                        .setOffset(0, 7, -6.5)
                        .addModelLocation(SpecialModels.MOPED_COSMETIC_STOCK_TRAY.getModelLocation()))
                .addCosmetic(CosmeticProperties.builder(StandardCosmetics.FRONT_LIGHTS)
                        .setOffset(0, 10, 10.1719)
                        .addModelLocation(SpecialModels.MOPED_COSMETIC_STOCK_FRONT_LIGHT.getModelLocation()))
        );

        this.add(ModEntities.OFF_ROADER.get(), VehicleProperties.builder()
                .setAxleOffset(-1.0F)
                .setBodyTransform(Transform.create(1.4))
                .setDisplayTransform(Transform.create(0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 1.0))
                .setHeldOffset(0.0, 3.5, 0.0)
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.LEFT)
                        .setPosition(Wheel.Position.FRONT)
                        .setOffset(10.0, 0.0, 14.5)
                        .setScale(1.4F)
                        .setParticles(true))
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.RIGHT)
                        .setPosition(Wheel.Position.FRONT)
                        .setOffset(10.0, 0.0, 14.5)
                        .setScale(1.4F)
                        .setParticles(true))
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.LEFT)
                        .setPosition(Wheel.Position.REAR)
                        .setOffset(10.0, 0.0, -14.5)
                        .setScale(1.4F)
                        .setParticles(true))
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.RIGHT)
                        .setPosition(Wheel.Position.REAR)
                        .setOffset(10.0, 0.0, -14.5)
                        .setScale(1.4F)
                        .setParticles(true))
                .addSeat(Seat.of(5.0, 4.0, -3.0, true))
                .addSeat(Seat.of(-5.0, 4.0, -3.0))
                .addSeat(Seat.of(5.0, 11.5, -14.5))
                .addSeat(Seat.of(-5.0, 3.5, -18.9))
                .setCanChangeWheels(true)
                .setCanBePainted(true)
                .setCanFitInTrailer(false)
                .setCamera(CameraProperties.builder()
                        .setDistance(6.0))
                .addExtended(PoweredProperties.builder()
                        .setEngineType(EngineType.LARGE_MOTOR)
                        .setEnginePower(16F)
                        .setMinEnginePitch(0.8F)
                        .setMaxEnginePitch(1.6F)
                        .setFuelFillerTransform(Transform.create(-12.0, 10.5, -6.5, 0.0, -90, 0.0, 0.5))
                        .setIgnitionTransform(Transform.create(0.0, 7.0, 6.2, -67.5, 0.0, 0.0, 0.5))
                        .setFrontAxleOffset(14.5)
                        .setRearAxleOffset(-14.5)
                        .setEnergyCapacity(25000F)
                        .setEngineSound(ModSounds.ENTITY_JET_SKI_ENGINE.getId())
                        .build()));

        this.add(ModEntities.SPORTS_CAR.get(), VehicleProperties.builder()
                .setBodyTransform(Transform.create(1.6))
                .setCanChangeWheels(true)
                .setCanBePainted(true)
                .addWheel(Wheel.builder()
                        .setPosition(Wheel.Position.FRONT)
                        .setSide(Wheel.Side.LEFT)
                        .setOffset(6.5, 0.25, 12.5)
                        .setScale(0.9))
                .addWheel(Wheel.builder()
                        .setPosition(Wheel.Position.FRONT)
                        .setSide(Wheel.Side.RIGHT)
                        .setOffset(6.5, 0.25, 12.5)
                        .setScale(0.9))
                .addWheel(Wheel.builder()
                        .setPosition(Wheel.Position.REAR)
                        .setSide(Wheel.Side.LEFT)
                        .setOffset(6.5, 0.25, -11.5)
                        .setScale(0.9)
                        .setParticles(true))
                .addWheel(Wheel.builder()
                        .setPosition(Wheel.Position.REAR)
                        .setSide(Wheel.Side.RIGHT)
                        .setOffset(6.5, 0.25, -11.5)
                        .setScale(0.9)
                        .setParticles(true))
                .addSeat(Seat.of(4, -2, -4, true))
                .setCamera(CameraProperties.builder()
                        .setDistance(5.0))
                .addExtended(PoweredProperties.builder()
                        .setEngineType(EngineType.LARGE_MOTOR)
                        .setEnginePower(20F)
                        .setFuelFillerTransform(Transform.create(-10.0, 6.5, -14.0, 0.0, -90.0, 0.0, 0.4))
                        .setIgnitionTransform(Transform.create(-5.0, 4.5, 6.5, -45.0, 0.0, 0.0, 0.5))
                        .setFrontAxleOffset(12.5)
                        .setRearAxleOffset(-11.5)
                        .setEnergyCapacity(20000F)
                        .setEngineSound(ModSounds.ENTITY_SPORTS_CAR_ENGINE.getId())
                        .setMinEnginePitch(0.9F)
                        .setMaxEnginePitch(1.5F)
                        .setMaxSteeringAngle(35F)
                        .setRenderEngine(true)
                        .setEngineTransform(Transform.create(0.0, 0.5, 11.5, 0.6))
                        .build())
                .addCosmetic(CosmeticProperties.builder(StandardCosmetics.HOOD)
                        .addModelLocation(SpecialModels.SPORTS_CAR_COSMETIC_STOCK_HOOD.getModelLocation())
                        .setOffset(0, 7.5, 7.5)
                        .addAction(new OpenableAction(OpenableAction.Axis.X, -60F, new ResourceLocation("vehicle:entity.vehicle.hood.open"), new ResourceLocation("vehicle:entity.vehicle.hood.close"), 12)))
                .addCosmetic(CosmeticProperties.builder(StandardCosmetics.FRONT_BUMPER)
                        .addModelLocation(SpecialModels.SPORTS_CAR_COSMETIC_STOCK_FRONT_BUMPER.getModelLocation())
                        .setOffset(0, 1, 19))
                .addCosmetic(CosmeticProperties.builder(StandardCosmetics.REAR_BUMPER)
                        .addModelLocation(SpecialModels.SPORTS_CAR_COSMETIC_STOCK_REAR_BUMPER.getModelLocation())
                        .setOffset(0, 1.5, -20))
                .addCosmetic(CosmeticProperties.builder(StandardCosmetics.LEFT_DOOR)
                        .addModelLocation(SpecialModels.SPORTS_CAR_COSMETIC_STOCK_LEFT_DOOR.getModelLocation())
                        .setOffset(8.5, 0, 5.5)
                        .addAction(new OpenableAction(OpenableAction.Axis.Y, -75F, new ResourceLocation("vehicle:entity.vehicle.door.open"), new ResourceLocation("vehicle:entity.vehicle.door.close"), 12)))
                .addCosmetic(CosmeticProperties.builder(StandardCosmetics.RIGHT_DOOR)
                        .addModelLocation(SpecialModels.SPORTS_CAR_COSMETIC_STOCK_RIGHT_DOOR.getModelLocation())
                        .setOffset(-8.5, 0, 5.5)
                        .addAction(new OpenableAction(OpenableAction.Axis.Y, 75F, new ResourceLocation("vehicle:entity.vehicle.door.open"), new ResourceLocation("vehicle:entity.vehicle.door.close"), 12)))
                .addCosmetic(CosmeticProperties.builder(StandardCosmetics.SPOILER)
                        .addModelLocation(SpecialModels.SPORTS_CAR_COSMETIC_STOCK_SPOILER.getModelLocation())
                        .setOffset(0, 7.5, -12.5)
                        .addAction(new OpenableAction(OpenableAction.Axis.X, 60F, new ResourceLocation("vehicle:entity.vehicle.door.open"), new ResourceLocation("vehicle:entity.vehicle.door.close"), 12)))
                .addCosmetic(CosmeticProperties.builder(StandardCosmetics.FRONT_LIGHTS)
                        .addModelLocation(SpecialModels.SPORTS_CAR_COSMETIC_STOCK_FRONT_LIGHTS.getModelLocation())
                        .setOffset(0, 3.5, 19))
                .addCosmetic(CosmeticProperties.builder(StandardCosmetics.REAR_LIGHTS)
                        .addModelLocation(SpecialModels.SPORTS_CAR_COSMETIC_STOCK_REAR_LIGHTS.getModelLocation())
                        .setOffset(0, 4, -19))
                .addCosmetic(CosmeticProperties.builder(StandardCosmetics.SEAT)
                        .addModelLocation(SpecialModels.SPORTS_CAR_COSMETIC_STOCK_SEAT.getModelLocation())
                        .setOffset(0, 0, 1))
                .addCosmetic(CosmeticProperties.builder(StandardCosmetics.DASHBOARD)
                        .addModelLocation(SpecialModels.SPORTS_CAR_COSMETIC_STOCK_DASHBOARD.getModelLocation())
                        .setOffset(0, 0, 1)));


        this.add(ModEntities.SPORTS_PLANE.get(), VehicleProperties.builder()
                .setBodyTransform(Transform.create(0.0, 0.0, -8.0, 0.0, 0.0, 0.0, 1.8))
                .setDisplayTransform(Transform.create(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.85))
                .addSeat(Seat.of(0.0, 0.0, 0.0, true))
                .addWheel(Wheel.builder()
                        .setPosition(Wheel.Position.FRONT)
                        .setOffset(0.0, -4.5, 20.25)
                        .setScale(0.45))
                .addWheel(Wheel.builder()
                        .setOffset(6.5, -4.5, 1.5)
                        .setScale(0.45))
                .addWheel(Wheel.builder()
                        .setOffset(-6.5, -4.5, 1.5)
                        .setScale(0.45))
                .setCanBePainted(true)
                .setCanFitInTrailer(false)
                .setCamera(CameraProperties.builder()
                        .setStrength(0.25F)
                        .setPosition(0, 2, 0)
                        .setDistance(7.0))
                .addExtended(PoweredProperties.builder()
                        .setEngineType(EngineType.LARGE_MOTOR)
                        .setEnginePower(24F)
                        .setFuelFillerTransform(Transform.create(-4.35, 6.0, -6.0, 0.0, -112.5, 0.0, 0.5))
                        .setIgnitionTransform(Transform.create(0.0, 3.75, 12.5, -67.5, 0.0, 0.0, 0.5))
                        .setFrontAxleOffset(20.25)
                        .setRearAxleOffset(1.5)
                        .setEnergyCapacity(75000F)
                        .setEnergyConsumptionPerTick(1.0F)
                        .setEngineSound(ModSounds.ENTITY_SPORTS_PLANE_ENGINE.getId())
                        .setMaxSteeringAngle(25F)
                        .build())
                .addExtended(PlaneProperties.builder()
                        .setFlapSensitivity(0.1F)
                        .setElevatorSensitivity(0.075F)
                        .setMaxTurnAngle(2F)
                        .build()));

        this.add(ModEntities.TRACTOR.get(), VehicleProperties.builder()
                .setAxleOffset(-3.0F)
                .setDisplayTransform(Transform.create(1.25))
                .setHeldOffset(0.0, 3.5, 0.0)
                .setCanTowTrailers(true)
                .setTowBarPosition(0.0, 0.0, -24.5)
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.LEFT)
                        .setPosition(Wheel.Position.FRONT)
                        .setOffset(8.0, 0.0, 14.0)
                        .setScale(0.9375, 0.0, 0.0)
                        .setAutoScale(true)
                        .setParticles(true))
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.RIGHT)
                        .setPosition(Wheel.Position.FRONT)
                        .setOffset(8.0, 0.0, 14.0)
                        .setScale(0.9375, 0.0, 0.0)
                        .setAutoScale(true)
                        .setParticles(true))
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.LEFT)
                        .setPosition(Wheel.Position.REAR)
                        .setOffset(8.0, 5.5, -14.5)
                        .setScale(1.875, 2.8, 2.8)
                        .setParticles(true))
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.RIGHT)
                        .setPosition(Wheel.Position.REAR)
                        .setOffset(8.0, 5.5, -14.5)
                        .setScale(1.875, 2.8, 2.8)
                        .setParticles(true))
                .addSeat(Seat.of(0.0, 9.0, -14.0, true))
                .setCanChangeWheels(true)
                .setCanBePainted(true)
                .setCanFitInTrailer(false)
                .setCamera(CameraProperties.builder()
                        .setDistance(5.0))
                .addExtended(PoweredProperties.builder()
                        .setEngineType(EngineType.LARGE_MOTOR)
                        .setEnginePower(8F)
                        .setMinEnginePitch(0.8F)
                        .setMaxEnginePitch(1.6F)
                        .setEngineTransform(Transform.create(0.0, 6.0, 7.5, 0.0, 0.0, 0.0, 0.85))
                        .setFuelFillerTransform(Transform.create(-6.0, 12.0, -0.5, 0.0, -90, 0.0, 0.6))
                        .setIgnitionTransform(Transform.create(-2.75, 12.0, -1.75, -45.0, 0.0, 0.0, 0.5))
                        .setFrontAxleOffset(14.0)
                        .setRearAxleOffset(-14.5)
                        .setShowExhaustFumes(true)
                        .setExhaustFumesPosition(-2, 32, 16) //TODO test this
                        .setRenderEngine(true)
                        .setEngineSound(ModSounds.ENTITY_TRACTOR_ENGINE.getId())
                        .build()));

        this.add(ModEntities.FERTILIZER.get(), VehicleProperties.builder()
                .setAxleOffset(-0.5F)
                .setBodyTransform(Transform.create(1.1))
                .setDisplayTransform(Transform.create(0.0, 0.0, -0.15, 0.0, 0.0, 0.0, 1.35))
                .setCanBePainted(true)
                .setCanFitInTrailer(false)
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.LEFT)
                        .setOffset(9.5, 0, 0)
                        .setScale(1.0, 1.25, 1.25))
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.RIGHT)
                        .setOffset(9.5, 0, 0)
                        .setScale(1.0, 1.25, 1.25))
                .addExtended(TrailerProperties.builder()
                        .setHitchOffset(-17)
                        .build()));

        this.add(ModEntities.FLUID_TRAILER.get(), VehicleProperties.builder()
                .setAxleOffset(-0.5F)
                .setBodyTransform(Transform.create(1.1))
                .setDisplayTransform(Transform.create(0.0, 0.0, -0.15, 0.0, 0.0, 0.0, 1.35))
                .setHeldOffset(0.0, 3.0, 0.0)
                .setCanBePainted(true)
                .setCanFitInTrailer(false)
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.LEFT)
                        .setOffset(9.5, 0, -2.5)
                        .setScale(1.0, 1.25, 1.25))
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.RIGHT)
                        .setOffset(9.5, 0, -2.5)
                        .setScale(1.0, 1.25, 1.25))
                .addExtended(TrailerProperties.builder()
                        .setHitchOffset(-25)
                        .build()));

        this.add(ModEntities.SEEDER.get(), VehicleProperties.builder()
                .setAxleOffset(-0.5F)
                .setBodyTransform(Transform.create(1.1))
                .setDisplayTransform(Transform.create(0.0, 0.0, -0.15, 0.0, 0.0, 0.0, 1.35))
                .setCanBePainted(true)
                .setCanFitInTrailer(false)
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.LEFT)
                        .setOffset(15.5, 0, 0)
                        .setScale(1.0, 1.25, 1.25))
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.RIGHT)
                        .setOffset(15.5, 0, 0)
                        .setScale(1.0, 1.25, 1.25))
                .addExtended(TrailerProperties.builder()
                        .setHitchOffset(-16)
                        .build()));

        this.add(ModEntities.STORAGE_TRAILER.get(), VehicleProperties.builder()
                .setAxleOffset(-0.5F)
                .setBodyTransform(Transform.create(1.1))
                .setDisplayTransform(Transform.create(0.0, 0.0, -0.15, 0.0, 0.0, 0.0, 1.35))
                .setCanTowTrailers(true)
                .setTowBarPosition(0.0, 0.0, -12.0)
                .setCanBePainted(true)
                .setCanFitInTrailer(false)
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.LEFT)
                        .setOffset(9.5, 0, 0)
                        .setScale(1.0, 1.25, 1.25))
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.RIGHT)
                        .setOffset(9.5, 0, 0)
                        .setScale(1.0, 1.25, 1.25))
                .addExtended(TrailerProperties.builder()
                        .setHitchOffset(-16)
                        .build()));

        this.add(ModEntities.VEHICLE_TRAILER.get(), VehicleProperties.builder()
                .setAxleOffset(-0.5F)
                .setBodyTransform(Transform.create(1.1))
                .setDisplayTransform(Transform.create(0.0, 0.0, -0.15, 0.0, 0.0, 0.0, 1.35))
                .setHeldOffset(0.0, 3.0, 0.0)
                .setCanBePainted(true)
                .setCanFitInTrailer(false)
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.LEFT)
                        .setOffset(12.5, 0, -2.5)
                        .setScale(1.0, 1.25, 1.25))
                .addWheel(Wheel.builder()
                        .setSide(Wheel.Side.RIGHT)
                        .setOffset(12.5, 0, -2.5)
                        .setScale(1.0, 1.25, 1.25))
                .addExtended(TrailerProperties.builder()
                        .setHitchOffset(-23)
                        .build()));

        this.add(new ResourceLocation("vehicle", "sofacopter"), VehicleProperties.builder()
                .setBodyTransform(Transform.create(0.0, 0.0, 0.0625, 0.0, 0.0, 0.0, 1.0))
                .setDisplayTransform(Transform.create(0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.25))
                .addSeat(Seat.of(0.0, 0.0, 0.0, true))
                .addExtended(PoweredProperties.builder()
                        .setEngineType(EngineType.SMALL_MOTOR)
                        .setEnginePower(15F)
                        .setFuelFillerTransform(Transform.create(0.0, 1.5, 8.0, 0.0, 0.0, 0.0, 0.45))
                        .setIgnitionTransform(Transform.create(-9.25, 8.0, 5.0, 0.0, 0.0, 0.0, 0.8))
                        .setEnergyCapacity(40000F)
                        .setEnergyConsumptionPerTick(0.5F)
                        .build()));
    }
}
